import React from 'react'
import '../../welcome.css'
import { FaFacebook, FaInstagram, FaTwitter } from "react-icons/fa";
import { BsCloudUpload, BsGraphUp, BsExclamationTriangle } from 'react-icons/bs';
function Welcome() {
    return (
        <div className="container-fluid">
            <header>
                <div id="intro">
                    <div class="mask rgba-black-strong">

                        <div class="container-fluid d-flex align-items-center justify-content-center h-100">

                            <div class="row d-flex justify-content-center text-center mt-5">

                                <div class="col-md-12">
                                    <h2 class="display-4 font-weight-bold white-text pt-5 mb-2">Things Platform</h2>
                                    <hr class="hr-light" />
                                    <h4 class="white-text my-4">A Complete solution for your IoT Hub</h4>

                                </div>

                            </div>

                        </div>

                    </div>
                </div>
            </header>
            <main className="mt-5">
                <section id="best-features" className="text-center">
                    <h2 class="mb-5 font-weight-bold">Best Features</h2>
                    <div class="row d-flex justify-content-center mb-4">
                        <div class="col-md-8">
                            <p class="grey-text">High speed evolution of IoT is generating more and more sensor data,these data have to be effectively stored and monitored.It demands an effective system for, </p>
                        </div>

                        <div class="row mt-5">
                            <div class="col-md-4 mb-5">
                                <i class="icon"><BsCloudUpload size={70} /></i>
                                <h4 class="my-4 font-weight-bold">Data Collection & Storage</h4>
                                <p class="grey-text">Collect data generated by your IoT devices and store it in our server securely.</p>
                            </div>

                            <div class="col-md-4 mb-1">
                                <i class="fa fa-heart fa-4x orange-text"><BsGraphUp size={70} /></i>
                                <h4 class="my-4 font-weight-bold">Real-time Montioring</h4>
                                <p class="grey-text">View your devices' data at any time any where.</p>
                            </div>
                            <div class="col-md-4 mb-1">
                                <i class="fa fa-bicycle fa-4x orange-text"><BsExclamationTriangle size={70} /></i>
                                <h4 class="my-4 font-weight-bold">Anomaly Detection & Alert System</h4>
                                <p class="grey-text">Detect anomalies present in your devices' dataset and get notified about the same.</p>
                            </div>
                        </div>
                    </div>
                </section>
                <hr className="my-5" />
            </main>
            <footer class="page-footer bg-dark text-light">
                <div class="container">

                    <div class="row py-4 d-flex align-items-center">


                        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
                            <h6 class="mb-0 white-text">Get connected with us on social networks!</h6>
                        </div>

                        <div class="col-md-6 col-lg-7 text-center text-md-right">

                            <a class="fb-ic mx-2 text-light" href="https://facebook.com">
                                <FaFacebook size={20} />
                            </a>

                            <a class="tw-ic mx-2 text-light" href="https://twitter.com">
                                <FaTwitter size={20} />
                            </a>

                            <a class="ins-ic mx-2 text-light" href="https://instagram.com">
                                <FaInstagram size={20} />
                            </a>
                        </div>


                    </div>

                </div>


            </footer>
        </div>
    )
}

export default Welcome;
