# Generated by Django 3.1.3 on 2020-11-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensormodel',
            name='is_parent',
            field=models.BooleanField(null=True),
        ),
    ]
