# Generated by Django 3.1.3 on 2020-11-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0002_sensormodel_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensormodel',
            name='is_root',
            field=models.BooleanField(null=True),
        ),
    ]
